services:
  crypto-trends:
    build: .
    image: crypto-trends:latest
    # still reads your .env (optional, since you baked it in at build time)
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
